# server port
server:
  port: 8080

---
# logging
logging:
  level:
    org.hibernate: debug
    com.stn.hpdp: debug

---
#spring default setting
spring:
  profiles:
    default: env

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: health, httptrace, info, metrics, prometheus

  sql:
    init:
      mode: never

